name: firmware_run_unit_tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: run unit tests
        run: |
          cd software/firmware/test
          ./runTests.sh
